### ISSUE TITLE
check failed

### ISSUE THREAD

**Issue by roga76** [kbyran/POINet#2]
I wanted to start the Dense Pose: python3 launch.py --config configs/densepose_baseline/dense_pose_r50v1.py --task visualize --image imgs/single.json

and get the following error:
05-28 03:13:44 Visualization type: densepose
05-28 03:13:44 {'image': {'gt_bbox': [0, 0, 256, 512],
           'im_id': 0,
           'image_url': 'imgs/pitt_512_256.jpg'}}
Traceback (most recent call last):
  File "launch.py", line 24, in <module>
    visualize_net(config=args.config, epoch=args.epoch, image=args.image)
  File "/home/nano-ai/projects/poi/poi/apis/visualize.py", line 34, in visualize_net
    pGen.batch_image, pIO.transform, pIO.data_name, None, logger)
  File "/home/nano-ai/projects/poi/poi/infer/mx.py", line 12, in __init__
    self.init_model(model_prefix, model_epoch, ctx_id)
  File "/home/nano-ai/projects/poi/poi/infer/mx.py", line 16, in init_model
    arg_params, aux_params = load_params(model_prefix, model_epoch)
  File "/home/nano-ai/projects/poi/poi/core/model.py", line 8, in load_params
    save_dict = nd.load("%s-%04d.params" % (prefix, epoch))
  File "/usr/local/lib/python3.6/dist-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "/home/nvidia/mxnet/mxnet/3rdparty/dmlc-core/src/io/local_filesys.cc", line 209
LocalFileSystem: Check failed: allow_null: :Open "logs/dense_pose_r50v1/checkpoint-0150.params": No such file or directory

any ideas?

**Comment by kbyran** [comment]
Download model params [here](https://drive.google.com/file/d/1Z5ljl9BQefCuS87TSPrSLD8isoyL0pQ-/view?usp=sharing) before visualization.
